function [ o1, x1 ] = constrline( ypx, xpx, interpol)
%   [ o1 x1 ] = constrline( x, y, interpol )

%   Reconstruct an extended line with the interpolant giving it two
%   position of this line to use in the lines_stereomatching.m
%   ypx = Is the y coordinates in pixel from the original image.
%   xpx = Is the x coordinates in pixel from the original image.
%   interpol = Is the interpolant that has been calculated from the
%   interppixel2line.m
%   interpol = the interpolante that was generated by interppixel2line.
%
%   created by M. Lopez-Caballero

% Postion of the particle
xrw = interpol(1).f(ypx,xpx);
yrw = interpol(2).f(ypx,xpx);
zrw = interpol(3).f(ypx,xpx);

% Light direction from the polynomial calibration RW
xrwd = interpol(4).f(ypx,xpx);
yrwd = interpol(5).f(ypx,xpx);
zrwd = interpol(6).f(ypx,xpx);

%
o1 = [xrw; yrw; zrw];
x1 = [xrw+xrwd; yrw+yrwd; zrw+zrwd];
end


